version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"   # MQTT TCP directo
      - "9001:9001"   # WebSocket backend
    networks:
      - dokploy-network
    #labels:
      #- traefik.enable=true
      #- traefik.docker.network=dokploy-network

      # Router HTTPS → backend 9001 (NO pongas "ws")
      #- traefik.http.routers.mqttws.rule=Host(`mqttws.generativo.cloud`)
      #- traefik.http.routers.mqttws.entrypoints=websecure
      #- traefik.http.routers.mqttws.tls=true
      #- traefik.http.routers.mqttws.tls.certresolver=letsencrypt

      #- traefik.http.services.mqttws.loadbalancer.server.port=9001
      #   ⬆  nada de ".server.scheme=ws"
networks:
  dokploy-network:
    external: true